"""empty message

Revision ID: 0b7f92811806
Revises: 
Create Date: 2025-06-26 18:17:34.073224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b7f92811806'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_menssages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('sented_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], use_alter=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.Integer(), nullable=False),
    sa.Column('user2_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('SOCIAL', 'ECONOMIC', 'STATISTICAL', name='datasource_type'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('saved_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('market_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('suscription_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETE', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('method', sa.Enum('CREDIT_CARD', 'PAYPAL', 'STRIPE', name='payment_methods'), nullable=False),
    sa.ForeignKeyConstraint(['suscription_id'], ['suscriptions.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['market_categories.id'], use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_data_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('data_source_id', sa.Integer(), nullable=False),
    sa.Column('relevance_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['data_source_id'], ['data_sources.id'], use_alter=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('upload_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('purpose_market', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Numeric(precision=1, scale=0), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('LIKE', 'DISLIKE', 'SHARE', 'REPORT', 'SAVE', name='reactions_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_text', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['survey_questions.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.String(length=120), nullable=False),
    sa.Column('type', sa.Enum('TEXT', 'SINGLE_CHOICE', 'MULTIPLE_CHOICE', name='survey_questions_type'), nullable=False),
    sa.ForeignKeyConstraint(['survey_id'], ['surveys.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('surveys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('plan', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('trend_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=False),
    sa.Column('competition_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('trend_score', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('success_probability', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=150), nullable=False),
    sa.Column('user_type', sa.Enum('ENTERPRISE', 'ENTREPRENEUR', 'CONSUMER', name='user_rol'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=False),
    sa.Column('avatar_url', sa.String(length=120), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('trend_analysis')
    op.drop_table('suscriptions')
    op.drop_table('surveys')
    op.drop_table('survey_questions')
    op.drop_table('survey_answers')
    op.drop_table('reactions')
    op.drop_table('ratings')
    op.drop_table('products')
    op.drop_table('product_images')
    op.drop_table('product_data_source')
    op.drop_table('product_categories')
    op.drop_table('payments')
    op.drop_table('notifications')
    op.drop_table('market_categories')
    op.drop_table('favorites')
    op.drop_table('data_sources')
    op.drop_table('comentaries')
    op.drop_table('chats')
    op.drop_table('chat_menssages')
    # ### end Alembic commands ###
