"""empty message

Revision ID: 2af22368f1ab
Revises: 0b7f92811806
Create Date: 2025-06-26 18:22:39.610403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2af22368f1ab'
down_revision = '0b7f92811806'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_menssages', 'users', ['sender_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'chat_menssages', 'chats', ['chat_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'chats', 'users', ['user1_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'chats', 'users', ['user2_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'comentaries', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'comentaries', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'favorites', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'favorites', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'notifications', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'payments', 'suscriptions', ['suscription_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product_categories', 'market_categories', ['category_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product_categories', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product_data_source', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product_data_source', 'data_sources', ['data_source_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'ratings', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'ratings', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reactions', 'products', ['product_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'reactions', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'survey_answers', 'survey_questions', ['question_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'survey_questions', 'surveys', ['survey_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'surveys', 'users', ['creator_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'suscriptions', 'users', ['user_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'trend_analysis', 'products', ['product_id'], ['id'], use_alter=True)
    op.add_column('users', sa.Column('name_user', sa.String(length=120), nullable=False))
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=120), nullable=False))
    op.drop_column('users', 'name_user')
    op.drop_constraint(None, 'trend_analysis', type_='foreignkey')
    op.drop_constraint(None, 'suscriptions', type_='foreignkey')
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_constraint(None, 'survey_questions', type_='foreignkey')
    op.drop_constraint(None, 'survey_answers', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'reactions', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'ratings', type_='foreignkey')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.drop_constraint(None, 'product_data_source', type_='foreignkey')
    op.drop_constraint(None, 'product_data_source', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'product_categories', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'notifications', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'favorites', type_='foreignkey')
    op.drop_constraint(None, 'comentaries', type_='foreignkey')
    op.drop_constraint(None, 'comentaries', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chats', type_='foreignkey')
    op.drop_constraint(None, 'chat_menssages', type_='foreignkey')
    op.drop_constraint(None, 'chat_menssages', type_='foreignkey')
    # ### end Alembic commands ###
