"""empty message

Revision ID: 2eeadd4f9889
Revises: 9a7889dafd28
Create Date: 2025-06-29 16:44:42.403044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2eeadd4f9889'
down_revision = '9a7889dafd28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'chat_messages', 'chats', ['chat_id'], ['id'], use_alter=True)
    op.create_foreign_key(None, 'chat_messages', 'users', ['sender_id'], ['id'], use_alter=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    op.drop_constraint(None, 'chat_messages', type_='foreignkey')
    # ### end Alembic commands ###
