"""empty message

Revision ID: 9a7889dafd28
Revises: 2af22368f1ab
Create Date: 2025-06-29 16:37:43.335521

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9a7889dafd28'
down_revision = '2af22368f1ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('sented_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], use_alter=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_menssages')
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_login_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
    op.alter_column('users', 'name',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.create_table('chat_menssages',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('chat_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content', mysql.VARCHAR(length=500), nullable=False),
    sa.Column('sented_at', mysql.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['chat_id'], ['chats.id'], name=op.f('chat_menssages_ibfk_2')),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('chat_menssages_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('chat_messages')
    # ### end Alembic commands ###
